name: Documentation
description: Report documentation issues or suggest improvements
title: '[Docs]: '
labels: ['documentation']
body:
  - type: markdown
    attributes:
      value: |
        Report documentation issues or suggest improvements.

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: Which documentation needs attention?
      options:
        - README.md
        - CONTRIBUTING.md
        - Code comments
        - Examples
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong or missing in the documentation?
      placeholder: Describe the documentation issue
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue? (file, section, line number)
      placeholder: README.md, Installation section, line 42
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should this be fixed or improved?
      placeholder: Proposed changes or additions
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information about the documentation issue
      placeholder: Screenshots, examples, links to good documentation

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to submit a pull request for this?
      options:
        - label: I am willing to submit a pull request for this documentation change
          required: false
